### ISSUE TITLE
等级过期问题

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#293]
辅导员，用户等级时间过后之后还可以正常使用，信息也显示还是原来的等级，没有回降为0
前后端均已经更新到最新。
开启debug之后的用户信息打开报错
									<div class="card-table">
										<div class="table-responsive">
											<table class="table">
												<tr>
													
													<th>IP</th>
													<th>归属地</th>
												</tr>
												<?php
$_from = $_smarty_tpl->tpl_vars['userip']->value;
if (!is_array($_from) && !is_object($_from)) {
settype($_from, 'array');
}
$__foreach_location_0_saved_item = isset($_smarty_tpl->tpl_vars['location']) ? $_smarty_tpl->tpl_vars['location'] : false;
$__foreach_location_0_saved_key = isset($_smarty_tpl->tpl_vars['single']) ? $_smarty_tpl->tpl_vars['single'] : false;
$_smarty_tpl->tpl_vars['location'] = new Smarty_Variable();
$_smarty_tpl->tpl_vars['single'] = new Smarty_Variable();
$_smarty_tpl->tpl_vars['location']->_loop = false;
foreach ($_from as $_smarty_tpl->tpl_vars['single']->value => $_smarty_tpl->tpl_vars['location']->value) {
$_smarty_tpl->tpl_vars['location']->_loop = true;

**Comment by leosejin** [comment]
更新之前就有这个问题，更新之后又自己测试了一下还是这样

**Comment by leosejin** [comment]
更新之前就有这个问题，更新之后又自己测试了一下还是这样

**Comment by glzjin** [comment]
@leosejin 1.请检查你的计划任务正常运行与否。
2.第二个问题请单独发一个issue详细描述。

谢谢。

**Comment by leosejin** [comment]
辅导员，查看了定时任务
[root@Open41 ~]# crontab -l
30 22 * * * php /home/wwwroot/www.xx.xx/xcat sendDiaryMail
*/1 * * * * php /home/wwwroot/www.xx.xx/xcat synclogin
*/1 * * * * php /home/wwwroot/www.xx.xx/xcat syncvpn
0 0 * * * php -n /home/wwwroot/www.xx.xx/xcat dailyjob
*/1 * * * * php /home/wwwroot/www.xx.xx/xcat checkjob    
*/1 * * * * php -n /home/wwwroot/www.xx.xx/xcat syncnas
[root@Open1 ~]# tail -f /var/log/cron
Oct  3 23:56:35 Open1 crontab[18973]: (root) BEGIN EDIT (root)
Oct  3 23:57:31 Open1 crontab[18973]: (root) REPLACE (root)
Oct  3 23:57:31 Open1 crontab[18973]: (root) END EDIT (root)
Oct  3 23:57:37 Open1 crontab[18978]: (root) LIST (root)
Oct  4 03:32:42 Open1 crontab[20156]: (root) LIST (root)
Oct  6 09:18:15 Open1 crontab[2415]: (root) LIST (root)
Oct  7 12:01:02 Open1 crontab[9718]: (root) LIST (root)
Oct  7 12:02:35 Open1 crontab[9738]: (root) LIST (root)

**Comment by WhoRUa** [comment]
我的也是这样，上次更新后这个Bug依然存在
用户群组（用户只能访问到组别等于这个数字或0的节点）
1
用户级别（用户只能访问到等级小于等于这个数字的节点）
4
用户等级过期时间(不过期就请不要动)
2016-10-06 12:15:36
用户账户过期时间(不过期就请不要动)

**Comment by glzjin** [comment]
请确定你的crontab在正常运行，并且 checkjob 执行无错误。

**Comment by WhoRUa** [comment]
systemctl status crond
● crond.service - Command Scheduler
   Loaded: loaded (/usr/lib/systemd/system/crond.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2016-10-05 17:33:23 CST; 3 days ago
 Main PID: 463 (crond)
   CGroup: /system.slice/crond.service
           └─463 /usr/sbin/crond -n

Oct 08 21:04:02 iZ28if crond[463]: sendmail: fatal: parameter inet_interfaces: no local interface found for ::1
Oct 08 21:04:02 iZ28if crond[463]: sendmail: fatal: parameter inet_interfaces: no local interface found for ::1

crontab -l
*/20 * * * * /sbin/ntpdate pool.ntp.org > /dev/null 2>&1
30 22 * * * php /data/wwwroot/www.u.top/xcat sendDiaryMail
*/1 * * * * php /data/wwwroot/www.u.top/xcat synclogin
*/1 * * * * php /data/wwwroot/www.u.top/xcat syncvpn
0 0 * * * php -n /data/wwwroot/www.u.top/xcat dailyjob
*/1 * * * * php /data/wwwroot/www.u.top/xcat checkjob 
*/1 * * * * php -n /data/wwwroot/www.u.top/xcat syncnas

刚才手动执行php /data/wwwroot/www.u.top/xcat checkjob 后可以了

**Comment by leosejin** [comment]
确实是crond的运行问题。谢谢解答！
