### ISSUE TITLE
the Ticket problem

### ISSUE THREAD

**Issue by fanyuanqi** [glzjin/ss-panel-v3-mod#406]
I find that in the file "app/Controllers/Admin/TicketController.php"  line 54

### if($status==1&&$ticket_main->status!=$status)

this line is commented out so the ticket can not be replied。

**Comment by fanyuanqi** [comment]
And I also find that 
1. the normal users can not reply the ticket.
2. even the problem above is fixed, after the Admin close the ticket, the ticket still can be replid by the Admin.
3. the ticket can not be deleted.

maybe there are more problem about the ticket, and I am willing to offer some help, if you need.
  
 Regards. 
           fanyuanqi

**Comment by glzjin** [comment]
@fanyuanqi fanyuanqi,

Thank you for your report.

0.This line code is doesn't cause the issue you report.I think it's due to you haven't configure mail module so the system can't  send email then return 500.

1.And normal user only can reply the ticket that they send.

2.Yes,You can reply the ticket you closed to reopen the ticket.

3.Yes,Don't delete by yourself.

Sincerely,
glzjin.


P.s:我说咱就俩中国人用英文累不累？
